apiVersion: apps/v1
kind: Deployment  
metadata:
  name: {{ .Values.webApp.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webApp.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.webApp.appName }}
    spec:
      containers:
        - name: {{ .Values.webApp.appName }}
          image: "{{ .Values.webApp.image.name }}:{{ .Values.webApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.webApp.port }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_name
      imagePullSecrets:
        - name: registrypullsecret

