
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webApp.appName }}
spec:
  replicas: 20
  selector:
    matchLabels:
      app: {{ .Values.webApp.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.webApp.appName }}
      annotations:
        gke-gcsfuse/volumes: "true" #Required
        gke-gcsfuse/cpu-limit: 500m
        gke-gcsfuse/memory-limit: 100Mi
        gke-gcsfuse/ephemeral-storage-limit: 5Gi
    spec:
      containers:
        - name: {{ .Values.webApp.appName }}
          image: "{{ .Values.webApp.image.name }}:{{ .Values.webApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.webApp.port }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_name 
      imagePullSecrets:
        - name: registrypullsecret
